spring.application.name=medicalclinic

spring.datasource.url=jdbc:postgresql://localhost:5432/demo
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:liquibase/db.changelog-master.yaml
spring.liquibase.default-schema=public
spring.liquibase.liquibase-schema=public
spring.liquibase.contexts=production
spring.liquibase.drop-first=false
spring.liquibase.parameters.schema.name=my_schema

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/medical-clinic/protocol/openid-connect/certs